const GAME_STATE = {
    START: "START",
    RUNNING: "RUNNING",
    PAUSED: "PAUSED",
    GAMEOVER: "GAMEOVER"
}

const FPS = 60;
const PLAYER_COLOR = "#E0E1DD";
const PLAYER_SIZE = 50;
// const ASTEROID_COLOR = "#778DA9";
const ASTEROID_COLOR = "#E0E1DD";
const ASTEROID_SIZE = 50;

const PLAYER_MAX_SPEED = 10;
const PLAYER_MOVING_FORCE = 2;
const PLAYER_FRICTION_FORCE = 0.15;
const PLAYER_ROTATION_SPEED = 0.1;
const ASTEROID_SPEED = {MIN: 1, MAX: 5};